Repository thrile/cirkopt, pull requests merged in 2021-03, with the labels that each got.

#57 Re-architect search algorithm and it's interface
  python/scripts/cirkopt.py
  python/scripts/single_param_sweep.py
  python/src/liberate.py
  python/src/liberate_grapher.py
  python/src/liberty_parser.py
  python/src/netlist_cost_functions.py
  python/src/search_algorithm.py
  python/src/single_param_sweep.py
  python/tests/test_liberate.py
  python/tests/test_search_algorithm.py
Labels: refactoring

#60 Add delay based cost function
  python/scripts/cirkopt.py
  python/src/netlist_cost_functions.py
  python/src/single_param_sweep.py
  python/tests/liberty_example.py
  python/tests/netlist_example.py
  python/tests/test_liberty_parser.py
  python/tests/test_netlist.py
  python/tests/test_netlist_cost_functions.py
Labels: enhancement

#65 Fixes from test runs
  liberate/.gitignore
  liberate/tcl/char.tcl
  python/scripts/cirkopt.py
  python/scripts/genetic_search.py
  python/src/genetic_search.py
  python/src/liberate.py
  python/src/netlist_cost_functions.py
  python/tests/liberty_example.py
  python/tests/netlist_example.py
  python/tests/test_netlist_cost_functions.py
Labels: bug, enhancement

#69 Use Range for genetic algo
  python/scripts/cirkopt.py
  python/scripts/genetic_search.py
  python/src/genetic_search.py
  python/src/liberate.py
  python/src/quantize.py
  python/tests/test_genetic_search.py
  python/tests/test_quantize.py
Labels: bug

#70 Dump and parse candidates as JSON objects
  python/Pipfile
  python/Pipfile.lock
  python/scripts/brute_force_search.py
  python/scripts/cirkopt.py
  python/scripts/genetic_search.py
  python/scripts/rename_netlists.py
  python/scripts/single_param_sweep.py
  python/src/file_io.py
  python/src/genetic_search.py
  python/src/json.py
  python/src/liberate.py
  python/src/netlist.py
  python/test.sh
  python/tests/mock_file.py
  python/tests/test_brute_force_search.py
  python/tests/test_genetic_search.py
  python/tests/test_json.py
  python/tests/test_liberty_parser.py
  python/tests/test_netlist.py
  python/tests/test_netlist_cost_functions.py
Labels: enhancement
